/**
 * Generate dist/sitemap.xml from the routes that actually prerendered.
 *
 * Runs after scripts/prerender.mjs, which writes dist/prerendered-routes.json.
 * Listing only routes that produced real HTML means the sitemap can never
 * advertise a URL that a crawler would receive as an empty shell.
 *
 * lastmod is emitted only where we genuinely know it (blog articles carry
 * updatedAt in their own data). Inventing lastmod dates for every URL is
 * worse than omitting the field - crawlers learn to distrust the signal.
 *
 * public/sitemap.xml stays in the repo as the fallback that ships if this
 * script ever fails; vite copies it into dist before this overwrites it.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";

const SITE = "https://ihaveallergy.com";
const DIST_DIR = resolve(process.cwd(), "dist");
const MANIFEST = join(DIST_DIR, "prerendered-routes.json");

// Legal/boilerplate pages: public and crawlable, but kept out of the sitemap
// so they do not compete with medical content for crawl attention.
const EXCLUDED = new Set(["/privacy", "/accessibility", "/security"]);

function lastmodForRoute(route, articles) {
  if (!route.startsWith("/blog/")) return null;
  const slug = decodeURIComponent(route.slice("/blog/".length));
  const article = articles.find((a) => a.slug === slug);
  return article?.updatedAt || article?.publishedAt || null;
}

/**
 * Blog metadata without importing TypeScript: pull slug/updatedAt pairs
 * straight out of the data file. Cheap, and avoids a second build step.
 */
function readBlogArticles() {
  const src = resolve(process.cwd(), "src/data/blog-articles.ts");
  if (!existsSync(src)) return [];
  const text = readFileSync(src, "utf8");
  const articles = [];
  const re = /slug:\s*"([^"]+)"[\s\S]*?publishedAt:\s*"([^"]+)"[\s\S]*?updatedAt:\s*"([^"]+)"/g;
  let m;
  while ((m = re.exec(text)) !== null) {
    articles.push({ slug: m[1], publishedAt: m[2], updatedAt: m[3] });
  }
  return articles;
}

function main() {
  if (!existsSync(MANIFEST)) {
    console.warn(
      "[sitemap] dist/prerendered-routes.json not found - keeping the " +
        "committed public/sitemap.xml. Run the prerender step first.",
    );
    process.exit(0);
  }

  const { routes } = JSON.parse(readFileSync(MANIFEST, "utf8"));
  const articles = readBlogArticles();

  const included = routes.filter((r) => !EXCLUDED.has(r));

  const urls = included
    .map((route) => {
      // Hebrew routes must be percent-encoded in XML, and & escaped.
      const loc = `${SITE}${encodeURI(route)}`.replace(/&/g, "&amp;");
      const lastmod = lastmodForRoute(route, articles);
      return lastmod
        ? `  <url><loc>${loc}</loc><lastmod>${lastmod}</lastmod></url>`
        : `  <url><loc>${loc}</loc></url>`;
    })
    .join("\n");

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs at build time. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

  writeFileSync(join(DIST_DIR, "sitemap.xml"), xml, "utf8");
  console.log(
    `[sitemap] Wrote dist/sitemap.xml - ${included.length} URLs ` +
      `(${routes.length - included.length} excluded).`,
  );
}

main();
