// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var notAuthenticated = {
  content: [{ type: "text", text: "Not authenticated." }],
  isError: true
};
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(data) {
  return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] };
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's identity and clinic roles. Use it to verify the connection works and what access is available.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_roles").select("role, clinic_id").eq("user_id", ctx.getUserId());
    if (error) return errorResult(error.message);
    return jsonResult({
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      roles: data ?? []
    });
  }
});

// src/lib/mcp/tools/list-clinics.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_clinics_default = defineTool2({
  name: "list_clinics",
  title: "List clinics",
  description: "List the active clinics the signed-in user can access, including name, city, phone and doctor details.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const { data, error } = await supabaseForUser(ctx).from("clinics").select("id, name, city, address, phone, email, doctor_name, doctor_specialty, is_active").eq("is_active", true).order("name");
    if (error) return errorResult(error.message);
    return jsonResult({ clinics: data ?? [] });
  }
});

// src/lib/mcp/tools/list-appointments.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var list_appointments_default = defineTool3({
  name: "list_appointments",
  title: "List appointments",
  description: "List clinic appointments in a date range. Returns scheduling data only (time, duration, status, clinic) and never patient identifiers or medical details.",
  inputSchema: {
    from: z.string().describe("Start of the range, ISO date or datetime. Defaults to now."),
    to: z.string().describe("End of the range, ISO date or datetime. Defaults to 14 days after `from`."),
    clinic_id: z.string().describe("Optional clinic id to filter by. Pass an empty string for all clinics."),
    limit: z.number().describe("Maximum rows to return. Capped at 200.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, clinic_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const start = from ? new Date(from) : /* @__PURE__ */ new Date();
    if (Number.isNaN(start.getTime())) return errorResult("Invalid `from` value.");
    const end = to ? new Date(to) : new Date(start.getTime() + 14 * 24 * 60 * 60 * 1e3);
    if (Number.isNaN(end.getTime())) return errorResult("Invalid `to` value.");
    const rowLimit = Math.min(Math.max(Number(limit) || 50, 1), 200);
    let query = supabaseForUser(ctx).from("appointments").select("id, clinic_id, scheduled_at, duration_minutes, status").gte("scheduled_at", start.toISOString()).lte("scheduled_at", end.toISOString()).order("scheduled_at").limit(rowLimit);
    if (clinic_id) query = query.eq("clinic_id", clinic_id);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({
      from: start.toISOString(),
      to: end.toISOString(),
      count: data?.length ?? 0,
      appointments: data ?? [],
      note: "Patient identifiers and medical details are intentionally excluded from MCP responses."
    });
  }
});

// src/lib/mcp/tools/schedule-summary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var schedule_summary_default = defineTool4({
  name: "get_schedule_summary",
  title: "Get schedule summary",
  description: "Aggregate appointment counts per day and per status for a date range. Contains no patient data.",
  inputSchema: {
    from: z2.string().describe("Start of the range, ISO date or datetime. Defaults to today."),
    days: z2.number().describe("Number of days to summarize, capped at 60. Defaults to 7.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, days }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const start = from ? new Date(from) : /* @__PURE__ */ new Date();
    if (Number.isNaN(start.getTime())) return errorResult("Invalid `from` value.");
    const span = Math.min(Math.max(Number(days) || 7, 1), 60);
    const end = new Date(start.getTime() + span * 24 * 60 * 60 * 1e3);
    const { data, error } = await supabaseForUser(ctx).from("appointments").select("scheduled_at, status").gte("scheduled_at", start.toISOString()).lte("scheduled_at", end.toISOString()).order("scheduled_at").limit(2e3);
    if (error) return errorResult(error.message);
    const byDay = {};
    const byStatus = {};
    for (const row of data ?? []) {
      const day = String(row.scheduled_at).slice(0, 10);
      byDay[day] = (byDay[day] ?? 0) + 1;
      const status = row.status ?? "unknown";
      byStatus[status] = (byStatus[status] ?? 0) + 1;
    }
    return jsonResult({
      from: start.toISOString(),
      to: end.toISOString(),
      total: data?.length ?? 0,
      by_day: byDay,
      by_status: byStatus
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "ftatmcyrmeyhghgckvbj";
var mcp_default = defineMcp({
  name: "ihaveallergy-mcp",
  title: "Dr. Anna Brameli Clinic MCP",
  version: "0.1.0",
  instructions: "Read-only tools for the Dr. Anna Brameli allergy clinic system. Use `whoami` to confirm access, `list_clinics` for clinic details, `list_appointments` for scheduling data in a date range, and `get_schedule_summary` for daily load. Responses never include patient names or medical records - protected health information stays inside the clinic system.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_clinics_default, list_appointments_default, schedule_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
